---
title: "Stat 360 Week 1 exercises"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. On which line does a get copied in the following example?
```{r}
a <- c(1, 5, 3, 2)
b <- a
b[[1]] <- 10
```
# a <- c(1, 5, 3, 2)
# tracemem(a)
# b <- a
# b[[1]] <- 10
# it shows tracemem[0x7fc4551378d8 -> 0x7fc44fa40c18]
# Ans: b[[1]] <- 10

2. In the following code chunk, does `x` get copied? Does `ll` get copied? Does  `ee` get copied?
```{r}
x <- rnorm(100); y <- rnorm(100)
ll <- list(x=x,y=y)
ll$x <- 1:100
ee <- rlang::env(x=x,y=y)
ee$x <- 1:100
```
# x <- rnorm(100); y <- rnorm(100)
# ll <- list(x=x,y=y)
# tracemem(ll) ; tracemem(ll[[1]])
# it shows tracemem[0x7fc4542691c8 -> 0x7fc453d52a08]
# Ans: Yes for ll, No for ee and x

3. Find the size of the objects x and y in the following code chunk.
Which is smaller? If instead of vectors from 1 to 10 they were vectors
from 1 to 1 million, which would be smaller?

```{r}
x <- c(1,2,3,4,5,6,7,8,9,10)
y <- 1:10
```
# lobstr::obj_size(x)
# lobstr::obj_size(y)
# Ans: 176 bytes for x and 96 bytes for y